# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       kde5-ksysguard

# >> macros
# << macros

Summary:    KDE Process Management application
Version:    4.97.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kde5-ksysguard.yaml
Source101:  kde5-ksysguard-rpmlintrc
Requires:   kde5-filesystem
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5Script)
BuildRequires:  kde5-rpm-macros
BuildRequires:  kf5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  kf5-umbrella
BuildRequires:  kf5-kcoreaddons-devel
BuildRequires:  kf5-ki18n-devel
BuildRequires:  kf5-kitemviews-devel
BuildRequires:  kf5-knewstuff-devel
BuildRequires:  kf5-kconfig-devel
BuildRequires:  kf5-kiconthemes-devel
BuildRequires:  kf5-kdelibs4support-devel
BuildRequires:  kf5-ksysguard-devel
BuildRequires:  lm_sensors-devel
BuildRequires:  desktop-file-utils
Provides:   ksysguard = %{version}-%{release}
Conflicts:   kde-runtime

%description
KDE Process Management application.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%kde5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kde5_make_install
# << install pre

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%doc COPYING COPYING.DOC README
%{_kde5_bindir}/ksysguard
%{_kde5_bindir}/ksysguardd
%{_kde5_libdir}/libkdeinit5_ksysguard.so
%{_kde5_datadir}/ksysguard
%{_kde5_sysconfdir}/xdg/ksysguard.knsrc
%{_kde5_sysconfdir}/ksysguarddrc
%{_datadir}/applications/ksysguard.desktop
%{_datadir}/doc/HTML/en/ksysguard
%{_datadir}/icons/oxygen/*/actions/*.png
%{_datadir}/knotifications5/ksysguard.notifyrc
# >> files
# << files
